In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
columns = ['age' ,'sex' , 'cp' ,'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num']

In [4]:
df = pd.read_csv("processed.cleveland.data" , sep =',', names = columns)

In [5]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [6]:
# convert nums value into 0 or 1
df['num'] = df.num.map({0:0 , 1:1,2:1, 3:1, 4:1})

In [7]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [8]:
x = df.iloc[: , :-1].values
y= df.iloc[: ,-1].values

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [12]:
# apply support vector machine
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train1 = scaler.fit_transform(x_train)
x_test1 = scaler.transform(x_test)

In [14]:
from sklearn.svm import SVC
model = SVC(kernel = 'rbf')
model.fit(x_train1, y_train)
test_score = model.score(x_test1 , y_test)
train_score = model.score(x_train1 , y_train)

In [15]:
test_score

0.8444444444444444

In [16]:
train_score

0.9130434782608695

In [22]:
# apply naive Bayes
from sklearn.naive_bayes import GaussianNB
model2 = GaussianNB()
model2.fit(x_train, y_train)
train_score = model2.score(x_train , y_train)
test_score = model2.score(x_test, y_test)

In [23]:
train_score

0.855072463768116

In [24]:
test_score

0.8444444444444444

In [25]:
# apply logistic regression
from sklearn.linear_model import LogisticRegression
model3 = LogisticRegression(solver = 'liblinear')
model3.fit(x_train, y_train)
model3.score(x_test, y_test)

0.8444444444444444

In [26]:
model3.score(x_train, y_train)

0.8695652173913043

In [27]:
# decision Tree
from sklearn.tree import DecisionTreeClassifier
model4 = DecisionTreeClassifier()
model4.fit(x_train, y_train)
model4.score(x_test, y_test)

0.7222222222222222

In [28]:
model4.score(x_train, y_train)

1.0

In [29]:
# apply random forest 
from sklearn.ensemble import RandomForestClassifier
model5 = RandomForestClassifier()
model5.fit(x_train, y_train)
model5.score(x_test, y_test)

0.7777777777777778

In [30]:
model5.score(x_train, y_train)

1.0