In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("emp.csv")

In [3]:
df.head()

     id         name gender  age  salary
0  1001   Ganesh Rao      M   25      20
1  1002      Lakshmi      F   22      20
2  1003  Vinod Kumar      M   30      22
3  1004       Neelam      F   33      30
4  1005      Reethu       F   21      19

In [4]:
df[df['age'] == 30]

     id         name gender  age  salary
2  1003  Vinod Kumar      M   30      22
6  1007     Kulkarni      M   30      24

In [5]:
df[df.age == 30].name

2    Vinod Kumar
6       Kulkarni
Name: name, dtype: object

In [8]:
df[df.age == 30][['id', 'name']] # display multiple columns

     id         name
2  1003  Vinod Kumar
6  1007     Kulkarni

In [11]:
df[(df.salary == 20) & (df.age ==22)][['id', 'name']]

     id     name
1  1002  Lakshmi

In [12]:
df[(df.age == 22)| (df.salary == 20)]

     id        name gender  age  salary
0  1001  Ganesh Rao      M   25      20
1  1002     Lakshmi      F   22      20

In [13]:
len(df)

10

In [14]:
df.shape

(10, 5)

In [15]:
df['age'].unique()

array([25, 22, 30, 33, 21, 40, 29], dtype=int64)

In [16]:
df[df.gender == 'M'].sort_values('age')

     id             name gender  age  salary
0  1001       Ganesh Rao      M   25      20
7  1008  Vishal Muhammad      M   29      19
2  1003      Vinod Kumar      M   30      22
6  1007         Kulkarni      M   30      24
5  1006    Gaurav Pandey      M   40      25
9  1010   Ankhit Chandra      M   40      26

In [17]:
df[df.gender == 'M'].sort_values('age' ,ascending = False) # decending order

     id             name gender  age  salary
5  1006    Gaurav Pandey      M   40      25
9  1010   Ankhit Chandra      M   40      26
2  1003      Vinod Kumar      M   30      22
6  1007         Kulkarni      M   30      24
7  1008  Vishal Muhammad      M   29      19
0  1001       Ganesh Rao      M   25      20

In [18]:
df.groupby(['gender' , 'age']).size().to_frame('count')

            count
gender age
F      21       1
       22       1
       25       1
       33       1
M      25       1
       29       1
       30       2
       40       2

In [19]:
df.groupby(['gender' , 'age']).size().to_frame('count').reset_index()

  gender  age  count
0      F   21      1
1      F   22      1
2      F   25      1
3      F   33      1
4      M   25      1
5      M   29      1
6      M   30      2
7      M   40      2

In [20]:
df.groupby(['gender' , 'age']).size().to_frame('count').reset_index().sort_values('age', ascending = False)

  gender  age  count
7      M   40      2
3      F   33      1
6      M   30      2
5      M   29      1
2      F   25      1
4      M   25      1
1      F   22      1
0      F   21      1

In [23]:
df[df.age.isin([25,30,40])]

     id            name gender  age  salary
0  1001      Ganesh Rao      M   25      20
2  1003     Vinod Kumar      M   30      22
5  1006   Gaurav Pandey      M   40      25
6  1007        Kulkarni      M   30      24
8  1009     Meena Singh      F   25      21
9  1010  Ankhit Chandra      M   40      26

In [24]:
df[~df.age.isin([25,30,40])]

     id             name gender  age  salary
1  1002          Lakshmi      F   22      20
3  1004           Neelam      F   33      30
4  1005          Reethu       F   21      19
7  1008  Vishal Muhammad      M   29      19

In [26]:
df.nlargest(4, columns = 'salary')

     id            name gender  age  salary
3  1004          Neelam      F   33      30
9  1010  Ankhit Chandra      M   40      26
5  1006   Gaurav Pandey      M   40      25
6  1007        Kulkarni      M   30      24

In [27]:
df.nsmallest(4, columns = 'salary')

     id             name gender  age  salary
4  1005          Reethu       F   21      19
7  1008  Vishal Muhammad      M   29      19
0  1001       Ganesh Rao      M   25      20
1  1002          Lakshmi      F   22      20

In [28]:
df.loc[df['salary'] == 20 , 'salary' ] = 21

In [29]:
df

     id             name gender  age  salary
0  1001       Ganesh Rao      M   25      21
1  1002          Lakshmi      F   22      21
2  1003      Vinod Kumar      M   30      22
3  1004           Neelam      F   33      30
4  1005          Reethu       F   21      19
5  1006    Gaurav Pandey      M   40      25
6  1007         Kulkarni      M   30      24
7  1008  Vishal Muhammad      M   29      19
8  1009      Meena Singh      F   25      21
9  1010   Ankhit Chandra      M   40      26

In [31]:
df = df.drop(df[df.salary == 21].index)

In [32]:
df

     id             name gender  age  salary
2  1003      Vinod Kumar      M   30      22
3  1004           Neelam      F   33      30
4  1005          Reethu       F   21      19
5  1006    Gaurav Pandey      M   40      25
6  1007         Kulkarni      M   30      24
7  1008  Vishal Muhammad      M   29      19
9  1010   Ankhit Chandra      M   40      26

In [33]:
df.filter(regex = '^s' , axis = 1) # ^satrt with s

   salary
2      22
3      30
4      19
5      25
6      24
7      19
9      26

In [35]:
df.filter(regex = 'e$' , axis = 1) #  $ end with s

Empty DataFrame
Columns: []
Index: [2, 3, 4, 5, 6, 7, 9]