In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("homeprices.csv")

In [3]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [4]:
df1 = df.copy()

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [8]:
df1.town = le.fit_transform(df1.town)

In [9]:
df1

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [10]:
df2 = df.copy()

In [13]:
dummies = pd.get_dummies(df2.town).astype('int')

In [14]:
dummies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [15]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()

In [16]:
df3 = df.copy()

In [17]:
df3.town = Le.fit_transform(df3.town)

In [18]:
df3

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [20]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown = 'ignore')

In [21]:
x1 = ohe.fit_transform(df3[['town']])

In [22]:
x1

<13x3 sparse matrix of type '<class 'numpy.float64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [27]:
x1 = pd.DataFrame(x1.toarray())

AttributeError: 'DataFrame' object has no attribute 'toarray'

In [28]:
x1 = x1.astype('int')

In [29]:
x1

    0  1  2
0   1  0  0
1   1  0  0
2   1  0  0
3   1  0  0
4   1  0  0
5   0  0  1
6   0  0  1
7   0  0  1
8   0  0  1
9   0  1  0
10  0  1  0
11  0  1  0
12  0  1  0

In [31]:
dummies = pd.get_dummies(df.town).astype('int')

In [32]:
dummies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [33]:
dummies = dummies.drop(['west windsor'], axis = 'columns')

In [34]:
dummies

    monroe township  robinsville
0                 1            0
1                 1            0
2                 1            0
3                 1            0
4                 1            0
5                 0            0
6                 0            0
7                 0            0
8                 0            0
9                 0            1
10                0            1
11                0            1
12                0            1

In [35]:
merged = pd.concat([df , dummies] , axis = 'columns')
merged

               town  area   price  monroe township  robinsville
0   monroe township  2600  550000                1            0
1   monroe township  3000  565000                1            0
2   monroe township  3200  610000                1            0
3   monroe township  3600  680000                1            0
4   monroe township  4000  725000                1            0
5      west windsor  2600  585000                0            0
6      west windsor  2800  615000                0            0
7      west windsor  3300  650000                0            0
8      west windsor  3600  710000                0            0
9       robinsville  2600  575000                0            1
10      robinsville  2900  600000                0            1
11      robinsville  3100  620000                0            1
12      robinsville  3600  695000                0            1

In [36]:
final = merged.drop(['town'], axis = 'columns')

In [37]:
final

    area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [38]:
x = final.drop(['price'] , axis = 'columns')

In [39]:
x

    area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [40]:
y = final['price']

In [41]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [42]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [43]:
reg.fit(x , y)

LinearRegression()

In [45]:
reg.predict([[2800 , 0 ,1]])

C:\Users\kunal  kumar  pandey\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

In [46]:
reg.predict([[3400 , 0 ,0]])

C:\Users\kunal  kumar  pandey\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.66845839])

In [47]:
reg.score(x,y)

0.9573929037221872

In [48]:
import joblib
joblib.dump(reg ,"Using_onehotencoding_House_price_predication.pkl")

['Using_onehotencoding_House_price_predication.pkl']