In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("smsspamcollection/SMSSpamCollection", sep='\t', header=None, names=['Status', 'Message'])

df.head()

  Status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
len(df)

5572

In [8]:
len(df[df.Status == 'spam'])

747

In [9]:
len(df[df.Status == 'ham'])

4825

In [10]:
# convert spam as 0 and ham is 1
df.loc[df["Status"] == 'spam' , "status"] = 0
df.loc[df["Status"] == 'ham' , "status"] = 1

In [11]:
df.head()

  Status                                            Message  status
0    ham  Go until jurong point, crazy.. Available only ...     1.0
1    ham                      Ok lar... Joking wif u oni...     1.0
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...     0.0
3    ham  U dun say so early hor... U c already then say...     1.0
4    ham  Nah I don't think he goes to usf, he lives aro...     1.0

In [12]:
df['Status'] = df['Status'].map({'spam': 0, 'ham': 1})

In [13]:
df.head()

   Status                                            Message  status
0       1  Go until jurong point, crazy.. Available only ...     1.0
1       1                      Ok lar... Joking wif u oni...     1.0
2       0  Free entry in 2 a wkly comp to win FA Cup fina...     0.0
3       1  U dun say so early hor... U c already then say...     1.0
4       1  Nah I don't think he goes to usf, he lives aro...     1.0

In [14]:
df.drop('status', axis=1, inplace=True)

In [15]:
df.head()

   Status                                            Message
0       1  Go until jurong point, crazy.. Available only ...
1       1                      Ok lar... Joking wif u oni...
2       0  Free entry in 2 a wkly comp to win FA Cup fina...
3       1  U dun say so early hor... U c already then say...
4       1  Nah I don't think he goes to usf, he lives aro...

In [16]:
x = df["Message"]
y = df["Status"]

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y ,test_size =0.3 )

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [22]:
cv = CountVectorizer()

In [23]:
# count the frequecny of the word in dataset 
x_traincv = cv.fit_transform(x_train)
x_testcv = cv.transform(x_test)

In [24]:
# befroe train the model take y as int
y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [25]:
mnb = MultinomialNB()

In [28]:
mnb.fit(x_traincv , y_train)

MultinomialNB()

In [29]:
mnb.score(x_testcv , y_test)

0.9820574162679426

In [30]:
x_test.iloc[0]

'K..k.:)congratulation ..'

In [31]:
pred = mnb.predict(x_testcv[0])

In [32]:
pred

array([1])

In [33]:
x_test.iloc[11]

'Ok k..sry i knw 2 siva..tats y i askd..'

In [34]:
mnb.predict(x_testcv[11])

array([1])

In [35]:
mnb.predict(x_testcv[15])

array([1])

In [36]:
mnb.predict(x_testcv[5])

array([1])

In [37]:
mnb.predict(x_testcv[21])

array([1])

In [38]:
mnb.predict(x_testcv[17])

array([1])

In [39]:
ex = ['free viagra now ', 'hi, can we play golf tomorrow ?']

In [40]:
test = cv.transform(ex)

In [41]:
pred = mnb.predict(test)

In [42]:
pred

array([0, 1])